[package]
name = "day19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
thiserror = "1"
anyhow = "1"
log = "0.4"
pretty_env_logger = "0.4"
pretty_assertions = "1"
cached = "0.23.0"
