[package]
name = "day14"
version = "0.1.0"
authors = ["Matthew Sherborne <msherborne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"

[dev-dependencies]
pretty_assertions = "0.6.1"
